### ISSUE TITLE
More tolerance with finger movement while typing

### ISSUE THREAD

**Issue by ltlnx** [hiroshiyui/GuilelessBopomofo#14] opened 2021-07-16 05:22 UTC
**Describe the bug**
While typing, sometimes keys register a click (vibrates and shows a popup character) but doesn't type out the key.

**To Reproduce**
Having finger movement when typing (i.e. typing fast)

**Expected behavior**
All characters are typed out.

**Screenshots**
The video should explain it precisely:

https://user-images.githubusercontent.com/52026741/125895714-ded22105-a189-4a07-a1f9-f41e589a4fd1.mp4

**Smartphone**
 - OS: Android 10
 - Version: 1.3.4

**Comment by hiroshiyui** [comment] 2021-07-18 13:20
@ltlnx In the screen recording, most of key touching gestures seem like not taps. And why I don't trigger valid keypress if user touch and move too fast from a key, is because sometimes user find her/him touched a wrong key, then the 'move out' will cancel the keypress. It's by design to fit my requirement.

Anyway, any furthur discussions are welcomed, however I must say I will spend lesser time on this project, because my financial situation is getting worse and worse these days. This project brings me no job chances from beginning till now, I have to consider other ways to make money and keep my life quality.

**Comment by hiroshiyui** [comment] 2022-04-30 09:01
@ltlnx Recently I made several adjustments to improve key-cap touching experiences, would you please do some validations for me?

**Comment by ltlnx** [comment] 2022-04-30 21:34
Sure! Is the change present in the latest version?

**Comment by ltlnx** [comment] 2022-05-01 08:15
After some hours of usage I can confirm that the typing experience is a lot better. I can now type with my thumbs instead of thumbtips :) Thanks! Should I close the issue?

**Comment by hiroshiyui** [comment] 2023-02-01 15:27
Fixed in da20aac3fa5f7549e7394da464c01993df4ccb9e

**Closed by hiroshiyui** 2023-02-01 15:27 UTC
