### ISSUE TITLE
Backspace button speed

### ISSUE THREAD

**Issue by ltlnx** [hiroshiyui/GuilelessBopomofo#6] opened 2021-01-27 12:37 UTC
Hello, 
The backspace button seems to lag when deleting words. Occurs on both Chinese and English.
Can anyone confirm?

**Comment by hiroshiyui** [comment] 2021-01-27 12:50
@ltlnx Yes it's by design, an initial delay has been triggered everytime to make "rate limitation". I may adjust the delay time value shorter.

**Comment by hiroshiyui** [comment] 2021-01-27 13:37
@ltlnx By the release 1.2.6, the issue should be resolved as a lowered delay time. However I am not sure if you feel it becomes OK or worse, the "magic number" of delay time make different experiences for different person. If you still getting unsatisfied, I may try other approaches to adjust the behavior of rate-limiter.

**Comment by hiroshiyui** [comment] 2021-01-27 13:50
Mmm, sorry, I found that I missed a place about "single click" of Backspace, the existent modification is for long-click. Will be fixed in release 1.2.7.

**Comment by ltlnx** [comment] 2021-01-28 15:49
Hello,
The backspace function works great in the new version! Google and Swiftkey have faster continuous deletion speed, but it's ok for the time being.

**Comment by ltlnx** [comment] 2021-04-23 00:46
After some months of use, I feel that the delete speed is still a bit slow. Could you speed it up a bit more to conform with other English keyboards? Thanks in advance.

**Comment by hiroshiyui** [comment] 2021-04-23 14:57
@ltlnx It's would be repeat quicker in 1.2.13, please give it a try. :-)

**Comment by ltlnx** [comment] 2021-04-30 08:21
Hi, 
Sorry for the late reply. The release doesn't contain an APK (only source code), can you build it then upload?

**Comment by hiroshiyui** [comment] 2021-04-30 10:39
@ltlnx The APK file has been added for the release.

**Closed** 2021-05-06 16:44 UTC
